project:
  type: book
  output-dir: docs
  post-render:
    - touch docs/.nojekyll

book:
  title: "Structural Econometrics with Julia"
  author: "Joseph Mullins"
  chapters:
    - index.qmd
    #- intro.qmd
    - part: models.qmd
      chapters:
      - models/generalized_roy.qmd
      - models/search.qmd
      - models/savings.qmd
      - models/entry-exit.qmd
      - models/dynamic-labor-supply.qmd
    - lectures/why_models.qmd
    - part: lectures/identification.qmd
      chapters:
      - lectures/identification_roy.qmd
      - lectures/identification_search.qmd
      - lectures/identification_labor_supply.qmd
    - part: Extremum Estimators
      chapters:
      - lectures/extremum_intro_examples.qmd
      - lectures/extremum_theory.qmd
    - part: Simulation Methods
    - part: lectures/discrete-choice.qmd
    #- summary.qmd
    - references.qmd
  appendices:
    - appendices/data.qmd
    - appendices/autodiff.qmd
    - appendices/performance.qmd

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    fig-format: png



